# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate README meta data

on:
  push:
    # only core workspace
    paths:
      - 'packages/core/**'
    branches:
      - 'master'

jobs:
#  contrib-readme-job:
#    runs-on: ubuntu-latest
#    name: A job to automate contrib in readme
#    steps:
#      - name: Contribute List
#        uses: akhilmhdh/contributors-readme-action@v2.3.6
#        env:
#          GITHUB_TOKEN: ${{ secrets.PAT }}

  build-dist:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install --no-frozen-lockfile
          pnpm install -g istanbul-badges-readme

      - name: Generate coverage and badges
        run: |
          pnpm run coverage
          pnpm run coverage:badges

      - name: Commit and push changes
        run: |
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          git config --local user.email "yijie4188@gmail.com" && git config --local user.name "YiJie"
          git add .
          git commit -m "chore: update coverage and badges"
          git push origin HEAD:${{ github.ref }}
